# Forest Explorer Kenya
## Exploratory Data Analysis (EDA) of GBIF Wildlife Data

This notebook explores wildlife occurrence data downloaded from the GBIF API.
The goal is to understand the dataset before cleaning and transforming it for the Forest Explorer Kenya application.

## 1. Import Required Libraries

In [1]:
import json
import pandas as pd

## 2. Load the GBIF Dataset

In [2]:

with open("../data/raw/gbif/gbif_test.json", "r", encoding="utf-8") as file:
    data = json.load(file)

df = pd.DataFrame(data["results"])

## 3. Dataset Overview

In [3]:
df.head()

,key,datasetKey,publishingOrgKey,installationKey,hostingOrganizationKey,publishingCountry,protocol,lastCrawled,lastParsed,crawlId,...,catalogNumber,institutionCode,eventTime,identificationID,lifeStage,dynamicProperties,vitality,projectId,informationWithheld,infraspecificEpithet
0,5938027617,50c9509d-22c7-4a22-a47d-8c48425ef4a7,28eb1a3f-1c15-4a95-931a-4af90ecb574d,997448a8-f762-11e1-a439-00145eb45e9a,28eb1a3f-1c15-4a95-931a-4af90ecb574d,US,DWC_ARCHIVE,2026-07-14T11:30:32.113+00:00,2026-07-14T22:25:25.945+00:00,600,...,333126626,iNaturalist,09:01:39+03:00,745484060,NaN,NaN,NaN,NaN,NaN,NaN
1,5938027647,50c9509d-22c7-4a22-a47d-8c48425ef4a7,28eb1a3f-1c15-4a95-931a-4af90ecb574d,997448a8-f762-11e1-a439-00145eb45e9a,28eb1a3f-1c15-4a95-931a-4af90ecb574d,US,DWC_ARCHIVE,2026-07-14T11:30:32.113+00:00,2026-07-14T22:07:39.537+00:00,600,...,333143771,iNaturalist,09:35:00+03:00,745538151,NaN,NaN,NaN,NaN,NaN,NaN
2,5938030027,50c9509d-22c7-4a22-a47d-8c48425ef4a7,28eb1a3f-1c15-4a95-931a-4af90ecb574d,997448a8-f762-11e1-a439-00145eb45e9a,28eb1a3f-1c15-4a95-931a-4af90ecb574d,US,DWC_ARCHIVE,2026-07-14T11:30:32.113+00:00,2026-07-14T22:18:19.381+00:00,600,...,333560943,iNaturalist,11:36:00+03:00,746731412,NaN,NaN,NaN,NaN,NaN,NaN
3,5938062731,50c9509d-22c7-4a22-a47d-8c48425ef4a7,28eb1a3f-1c15-4a95-931a-4af90ecb574d,997448a8-f762-11e1-a439-00145eb45e9a,28eb1a3f-1c15-4a95-931a-4af90ecb574d,US,DWC_ARCHIVE,2026-07-14T11:30:32.113+00:00,2026-07-14T22:07:35.556+00:00,600,...,333150224,iNaturalist,17:02:00+03:00,745558394,Adult,"{""evidenceOfPresence"":""organism""}",alive,NaN,NaN,NaN
4,5938065096,50c9509d-22c7-4a22-a47d-8c48425ef4a7,28eb1a3f-1c15-4a95-931a-4af90ecb574d,997448a8-f762-11e1-a439-00145eb45e9a,28eb1a3f-1c15-4a95-931a-4af90ecb574d,US,DWC_ARCHIVE,2026-07-14T11:30:32.113+00:00,2026-07-14T21:22:01.083+00:00,600,...,333466472,iNaturalist,20:37:29+03:00,746461420,NaN,NaN,NaN,https://www.inaturalist.org/projects/afriherps,NaN,NaN

In [3]:
df.shape

(10, 96)

In [4]:
df.columns.tolist()

['key',
 'datasetKey',
 'publishingOrgKey',
 'installationKey',
 'hostingOrganizationKey',
 'publishingCountry',
 'protocol',
 'lastCrawled',
 'lastParsed',
 'crawlId',
 'extensions',
 'basisOfRecord',
 'occurrenceStatus',
 'classifications',
 'taxonKey',
 'kingdomKey',
 'phylumKey',
 'classKey',
 'orderKey',
 'familyKey',
 'genusKey',
 'speciesKey',
 'acceptedTaxonKey',
 'scientificName',
 'scientificNameAuthorship',
 'acceptedScientificName',
 'kingdom',
 'phylum',
 'order',
 'family',
 'genus',
 'species',
 'genericName',
 'specificEpithet',
 'taxonRank',
 'taxonomicStatus',
 'iucnRedListCategory',
 'dateIdentified',
 'decimalLatitude',
 'decimalLongitude',
 'coordinateUncertaintyInMeters',
 'continent',
 'stateProvince',
 'gadm',
 'year',
 'month',
 'day',
 'eventDate',
 'startDayOfYear',
 'endDayOfYear',
 'issues',
 'modified',
 'lastInterpreted',
 'references',
 'license',
 'isSequenced',
 'identifiers',
 'media',
 'facts',
 'relations',
 'isInCluster',
 'datasetName',
 'recordedBy',
 'identifiedBy',
 'dnaSequenceID',
 'nucleotideSequence',
 'geodeticDatum',
 'class',
 'countryCode',
 'recordedByIDs',
 'identifiedByIDs',
 'gbifRegion',
 'country',
 'publishedByGbifRegion',
 'rightsHolder',
 'identifier',
 'http://unknown.org/nick',
 'verbatimEventDate',
 'http://unknown.org/crawl_attempt',
 'http://unknown.org/status',
 'verbatimLocality',
 'collectionCode',
 'gbifID',
 'occurrenceID',
 'taxonID',
 'http://unknown.org/captive_cultivated',
 'catalogNumber',
 'institutionCode',
 'eventTime',
 'identificationID',
 'lifeStage',
 'dynamicProperties',
 'vitality',
 'projectId',
 'informationWithheld',
 'infraspecificEpithet']

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 96 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   key                                    10 non-null     int64
 1   datasetKey                             10 non-null     str
 2   publishingOrgKey                       10 non-null     str
 3   installationKey                        10 non-null     str
 4   hostingOrganizationKey                 10 non-null     str
 5   publishingCountry                      10 non-null     str
 6   protocol                               10 non-null     str
 7   lastCrawled                            10 non-null     str
 8   lastParsed                             10 non-null     str
 9   crawlId                                10 non-null     int64
 10  extensions                             10 non-null     object
 11  basisOfRecord                          10 non-null     str
 12  occurrenceStatus                       10 non-null     str
 13  classifications                        10 non-null     object
 14  taxonKey                               10 non-null     int64
 15  kingdomKey                             10 non-null     int64
 16  phylumKey                              10 non-null     int64
 17  classKey                               10 non-null     int64
 18  orderKey                               9 non-null      float64
 19  familyKey                              10 non-null     int64
 20  genusKey                               10 non-null     int64
 21  speciesKey                             10 non-null     int64
 22  acceptedTaxonKey                       10 non-null     int64
 23  scientificName                         10 non-null     str
 24  scientificNameAuthorship               9 non-null      str
 25  acceptedScientificName                 10 non-null     str
 26  kingdom                                10 non-null     str
 27  phylum                                 10 non-null     str
 28  order                                  9 non-null      str
 29  family                                 10 non-null     str
 30  genus                                  10 non-null     str
 31  species                                10 non-null     str
 32  genericName                            10 non-null     str
 33  specificEpithet                        10 non-null     str
 34  taxonRank                              10 non-null     str
 35  taxonomicStatus                        10 non-null     str
 36  iucnRedListCategory                    9 non-null      str
 37  dateIdentified                         10 non-null     str
 38  decimalLatitude                        10 non-null     float64
 39  decimalLongitude                       10 non-null     float64
 40  coordinateUncertaintyInMeters          9 non-null      float64
 41  continent                              10 non-null     str
 42  stateProvince                          10 non-null     str
 43  gadm                                   10 non-null     object
 44  year                                   10 non-null     int64
 45  month                                  10 non-null     int64
 46  day                                    10 non-null     int64
 47  eventDate                              10 non-null     str
 48  startDayOfYear                         10 non-null     int64
 49  endDayOfYear                           10 non-null     int64
 50  issues                                 10 non-null     object
 51  modified                               10 non-null     str
 52  lastInterpreted                        10 non-null     str
 53  references                             10 non-null     str
 54  license                                10 non-null     str
 55  isSequenced                            10 non-null     bool
 56  identifiers                            10 non-null     object
 57  media                                  10 non-null     object
 58  facts                                  10 non-null     object
 59  relations                              10 non-null     object
 60  isInCluster                            10 non-null     bool
 61  datasetName                            10 non-null     str
 62  recordedBy                             10 non-null     str
 63  identifiedBy                           10 non-null     str
 64  dnaSequenceID                          10 non-null     object
 65  nucleotideSequence                     10 non-null     object
 66  geodeticDatum                          10 non-null     str
 67  class                                  10 non-null     str
 68  countryCode                            10 non-null     str
 69  recordedByIDs                          10 non-null     object
 70  identifiedByIDs                        10 non-null     object
 71  gbifRegion                             10 non-null     str
 72  country                                10 non-null     str
 73  publishedByGbifRegion                  10 non-null     str
 74  rightsHolder                           10 non-null     str
 75  identifier                             10 non-null     str
 76  http://unknown.org/nick                10 non-null     str
 77  verbatimEventDate                      10 non-null     str
 78  http://unknown.org/crawl_attempt       10 non-null     str
 79  http://unknown.org/status              10 non-null     str
 80  verbatimLocality                       10 non-null     str
 81  collectionCode                         10 non-null     str
 82  gbifID                                 10 non-null     str
 83  occurrenceID                           10 non-null     str
 84  taxonID                                10 non-null     str
 85  http://unknown.org/captive_cultivated  10 non-null     str
 86  catalogNumber                          10 non-null     str
 87  institutionCode                        10 non-null     str
 88  eventTime                              10 non-null     str
 89  identificationID                       10 non-null     str
 90  lifeStage                              2 non-null      str
 91  dynamicProperties                      2 non-null      str
 92  vitality                               2 non-null      str
 93  projectId                              1 non-null      str
 94  informationWithheld                    2 non-null      str
 95  infraspecificEpithet                   1 non-null      str
dtypes: bool(2), float64(4), int64(15), object(12), str(63)
memory usage: 7.5+ KB

In [7]:
df.describe()

,key,crawlId,taxonKey,kingdomKey,phylumKey,classKey,orderKey,familyKey,genusKey,speciesKey,acceptedTaxonKey,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,year,month,day,startDayOfYear,endDayOfYear
count,1.000000e+01,10.0,1.000000e+01,10.0,10.0,1.000000e+01,9.000000e+00,10.00000,1.000000e+01,1.000000e+01,1.000000e+01,10.000000,10.000000,9.00000,10.0,10.0,10.000000,10.000000,10.000000
mean,5.938058e+09,600.0,4.710027e+06,1.0,44.0,1.159475e+06,7.997566e+05,6671.20000,3.503202e+06,4.556476e+06,4.710027e+06,-1.817523,36.704082,9564.00000,2026.0,1.0,2.900000,2.900000,2.900000
std,2.175460e+04,0.0,2.889737e+06,0.0,0.0,3.665705e+06,2.396771e+06,2416.66914,1.825366e+06,2.557901e+06,2.889737e+06,1.202821,1.887744,13317.97708,0.0,0.0,0.875595,0.875595,0.875595
min,5.938028e+09,600.0,2.440455e+06,1.0,44.0,2.120000e+02,7.210000e+02,2877.00000,2.433504e+06,2.440455e+06,2.440455e+06,-4.261918,34.985667,2.00000,2026.0,1.0,2.000000,2.000000,2.000000
25%,5.938038e+09,600.0,2.483923e+06,1.0,44.0,2.120000e+02,7.310000e+02,5299.25000,2.451063e+06,2.483923e+06,2.483923e+06,-2.366549,35.286293,43.00000,2026.0,1.0,2.000000,2.000000,2.000000
50%,5.938066e+09,600.0,3.857224e+06,1.0,44.0,2.855000e+02,7.320000e+02,5310.00000,2.487966e+06,3.857224e+06,3.857224e+06,-1.199188,35.857765,64.00000,2026.0,1.0,3.000000,3.000000,3.000000
75%,5.938072e+09,600.0,5.229453e+06,1.0,44.0,3.590000e+02,8.390000e+02,9301.00000,4.237840e+06,5.229453e+06,5.229453e+06,-1.061061,37.812890,11853.00000,2026.0,1.0,3.750000,3.750000,3.750000
max,5.938086e+09,600.0,1.069876e+07,1.0,44.0,1.159225e+07,7.191147e+06,9453.00000,7.716694e+06,9.163257e+06,1.069876e+07,-0.826978,39.964508,31448.00000,2026.0,1.0,4.000000,4.000000,4.000000

## 4. Missing Value Analysis

In [21]:
df.isnull().sum()

key                       0
datasetKey                0
publishingOrgKey          0
installationKey           0
hostingOrganizationKey    0
                         ..
dynamicProperties         8
vitality                  8
projectId                 9
informationWithheld       8
infraspecificEpithet      9
Length: 96, dtype: int64

## 5. Selecting Relevant Columns

The GBIF dataset contains many fields. For the Forest Explorer application,
we only keep the columns needed for mapping wildlife observations.

In [15]:
locations = df[[
    "scientificName",
    "country",
    "countryCode",
    "stateProvince",
    "verbatimLocality",
    "decimalLatitude",
    "decimalLongitude"
]]

locations.head()

,scientificName,country,countryCode,stateProvince,verbatimLocality,decimalLatitude,decimalLongitude
0,"Tursiops aduncus (Ehrenberg, 1833)",Kenya,KE,Kilifi,"Kilifi, KE",-3.430600,39.964508
1,"Buteo augur (Ruppell, 1836)",Kenya,KE,Narok,"Lolgorian, Kenya",-1.272472,34.985667
2,"Streptopelia capicola (Sundevall, 1857)",Kenya,KE,Narok,"Ololunga, Kenya",-1.124248,35.267638
3,"Anastomus lamelligerus Temminck, 1823",Kenya,KE,Nakuru,"Sulmac Village, Kenya",-0.826978,36.374481
4,"Trioceros jacksonii (Boulenger, 1896)",Kenya,KE,Nairobi,"Nairobi, Nairobi, KE",-1.379105,36.765167

## 6. Missing Values in Selected Columns

In [16]:
locations.isnull().sum()

scientificName      0
country             0
countryCode         0
stateProvince       0
verbatimLocality    0
decimalLatitude     0
decimalLongitude    0
dtype: int64

# Exploratory Data Analysis (EDA)

### 7.1 Species Frequency

This section identifies how many times each species appears in the dataset.

In [18]:
locations["scientificName"].value_counts()

scientificName
Tursiops aduncus (Ehrenberg, 1833)         1
Buteo augur (Ruppell, 1836)                1
Streptopelia capicola (Sundevall, 1857)    1
Anastomus lamelligerus Temminck, 1823      1
Trioceros jacksonii (Boulenger, 1896)      1
Ploceus rubiginosus Rüppell, 1840          1
Crocuta crocuta (Erxleben, 1777)           1
Hippopotamus amphibius Linnaeus, 1758      1
Colius striatus J.F.Gmelin, 1789           1
Giraffa tippelskirchi tippelskirchi        1
Name: count, dtype: int64

### 7.2 Observations by County

In [22]:
locations["stateProvince"].value_counts()

stateProvince
Narok           5
Kilifi          1
Nakuru          1
Nairobi         1
Taita Taveta    1
Kwale           1
Name: count, dtype: int64

### 7.3 Observations by Country

In [23]:
locations["country"].value_counts()

country
Kenya    10
Name: count, dtype: int64

### 7.4 Geographic Coordinates

In [24]:
locations[["decimalLatitude", "decimalLongitude"]].describe()

       decimalLatitude  decimalLongitude
count        10.000000         10.000000
mean         -1.817523         36.704082
std           1.202821          1.887744
min          -4.261918         34.985667
25%          -2.366549         35.286293
50%          -1.199188         35.857765
75%          -1.061061         37.812890
max          -0.826978         39.964508

# Key Findings

- The dataset contains 10 wildlife observations.
- There are no missing values in the selected columns.
- Every observation includes geographic coordinates.
- Wildlife observations come from several counties in Kenya.
- Each species appears once in this sample dataset.